name: Build Pakage
on: [pull_request]

jobs:
  build-flake:
    name: Build the flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .
